name: examples/llama2 (staging)

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
    - '.github/workflows/example-llama2-staging.yaml'
    - 'llama2/**'
    - '!llama2/README.md'

  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
    - '.github/workflows/example-llama2-staging.yaml'
    - 'llama2/**'
    - '!llama2/README.md'

  schedule:
  - cron: '0 4 * * 1-6' # Every work day at 4AM


env:
  UKC_METRO: ${{ vars.UKC_METRO }}
  UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
  KRAFTKIT_NO_CHECK_UPDATES: true
  KRAFTKIT_LOG_LEVEL: debug

jobs:
  integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      id: test
      uses: unikraft/kraftkit@staging
      continue-on-error: true
      with:
        run: |
          set -xe;

          cd llama2;

          kraft cloud deploy \
            --no-start \
            --memory 1024 \
            --name llama2-${GITHUB_RUN_ID} \
            --runtime index.unikraft.io/official-staging/llama2:latest \
            --subdomain llama2-${GITHUB_RUN_ID} \
            -p 443:8080 \
            .;

          # wait for the instance to start
          kraft cloud vm start -w 60s llama2-${GITHUB_RUN_ID};
          sleep 5;

          curl -Lv --fail-with-body --max-time 10 https://llama2-${GITHUB_RUN_ID}.${UKC_METRO}.kraft.host/api/llama2

    - name: Cleanup
      uses: unikraft/kraftkit@staging
      if: always()
      with:
        run: |
          set -xe;
          kraft cloud vm stop llama2-${GITHUB_RUN_ID} || true;
          kraft cloud vm logs llama2-${GITHUB_RUN_ID} || true;
          kraft cloud vm rm llama2-${GITHUB_RUN_ID} || true;
          kraft cloud img rm index.unikraft.io/test/llama2-${GITHUB_RUN_ID} || true;

    - name: Re-test with debug info
      id: re-test
      if: ${{ success() && steps.test.outcome == 'failure' }}
      uses: unikraft/kraftkit@staging
      with:
        run: |
          set -xe;

          cd llama2;

          kraft cloud deploy \
            --no-start \
            --memory 1024 \
            --name llama2-${GITHUB_RUN_ID}-dbg \
            --runtime index.unikraft.io/official-staging/llama2:latest-dbg \
            --subdomain llama2-${GITHUB_RUN_ID}-dbg \
            -p 443:8080 \
            .;

          # wait for the instance to start
          kraft cloud vm start -w 60s llama2-${GITHUB_RUN_ID}-dbg;
          sleep 5;

          curl -Lv --fail-with-body --max-time 10 https://llama2-${GITHUB_RUN_ID}-dbg.${UKC_METRO}.kraft.host/api/llama2

    - name: Cleanup Debug
      uses: unikraft/kraftkit@staging
      if: always()
      with:
        run: |
          set -xe;
          kraft cloud vm stop llama2-${GITHUB_RUN_ID}-dbg || true;
          kraft cloud vm logs llama2-${GITHUB_RUN_ID}-dbg || true;
          kraft cloud vm rm llama2-${GITHUB_RUN_ID}-dbg || true;
          kraft cloud img rm index.unikraft.io/test/llama2-${GITHUB_RUN_ID}-dbg || true;